name = "nucleo_g431kb"
description = ""
version = "0.1.0"

authors = ["Olivier Henley"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["nucleo", "stm32", "stm32g4", "embedded"]

[[depends-on]]
light_tasking_stm32g431 = "*"
gnat_arm_elf = "*"
[origin]
commit = "c6ad548c1162b002ced327e187b1d2922fcae59e"
url = "git+https://github.com/GNAT-Academic-Program/nucleo_g431kb.git"

